# Generated by Django 5.0.2 on 2024-03-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medicationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NurseServiceRate',
            fields=[
                ('nurseServiceRateID', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_service_rates', to='SCS.service')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceRate',
            fields=[
                ('doctorServiceRateID', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_service_rates', to='SCS.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('appointmentServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='SCS.appointment')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='SCS.service')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetableID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('doctor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_timetable', to='SCS.userprofile')),
                ('nurse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_timetable', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('repeatable', models.BooleanField()),
                ('dosage', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='SCS.appointment')),
                ('medication', models.ManyToManyField(related_name='prescriptions', to='SCS.medication')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to='SCS.userprofile')),
                ('practitioner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_prescription', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPartTime', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_user', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('dateIssued', models.DateField()),
                ('billingParty', models.BooleanField()),
                ('appointmentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='SCS.appointment')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_invoice', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('isPartTime', models.BooleanField(default=False)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('contactID', models.AutoField(primary_key=True, serialize=False)),
                ('contactType', models.CharField(max_length=100)),
                ('contactValue', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='SCS.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='SCS.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practicioner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_appointment', to='SCS.userprofile'),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='SCS.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('buildingName', models.CharField(max_length=100)),
                ('streetName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='SCS.userprofile')),
            ],
        ),
    ]
